/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaskalkulator;

/**
 *
 * @author Asus
 */
public class Kalkulator extends javax.swing.JFrame {
    String a="";
double b, a1, a2;
int pilih;

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        duanol = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton12.setText("Exit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);
        getContentPane().setLayout(null);

        hasil.setEditable(false);
        hasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(hasil);
        hasil.setBounds(39, 20, 516, 90);

        clear.setBackground(new java.awt.Color(0, 255, 204));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(438, 141, 117, 45);

        exit.setBackground(new java.awt.Color(0, 255, 204));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(39, 141, 116, 45);

        backspace.setBackground(new java.awt.Color(0, 255, 204));
        backspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backspace.setText("Backspace");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });
        getContentPane().add(backspace);
        backspace.setBounds(173, 141, 247, 45);

        tambah.setBackground(new java.awt.Color(51, 255, 51));
        tambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(438, 204, 116, 45);

        tiga.setBackground(new java.awt.Color(51, 255, 51));
        tiga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga);
        tiga.setBounds(304, 204, 116, 45);

        dua.setBackground(new java.awt.Color(255, 255, 0));
        dua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua);
        dua.setBounds(173, 204, 116, 45);

        empat.setBackground(new java.awt.Color(255, 255, 0));
        empat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat);
        empat.setBounds(39, 267, 116, 45);

        lima.setBackground(new java.awt.Color(255, 255, 0));
        lima.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima);
        lima.setBounds(173, 267, 116, 45);

        enam.setBackground(new java.awt.Color(51, 255, 51));
        enam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam);
        enam.setBounds(304, 267, 116, 45);

        kurang.setBackground(new java.awt.Color(51, 255, 51));
        kurang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang);
        kurang.setBounds(438, 267, 116, 45);

        tujuh.setBackground(new java.awt.Color(51, 255, 51));
        tujuh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh);
        tujuh.setBounds(39, 328, 116, 45);

        delapan.setBackground(new java.awt.Color(51, 255, 51));
        delapan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan);
        delapan.setBounds(173, 328, 116, 45);

        sembilan.setBackground(new java.awt.Color(255, 255, 0));
        sembilan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan);
        sembilan.setBounds(304, 328, 116, 45);

        satu.setBackground(new java.awt.Color(255, 255, 0));
        satu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu);
        satu.setBounds(39, 204, 116, 45);

        duanol.setBackground(new java.awt.Color(51, 255, 51));
        duanol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        duanol.setText("00");
        duanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duanolActionPerformed(evt);
            }
        });
        getContentPane().add(duanol);
        duanol.setBounds(173, 389, 116, 45);

        nol.setBackground(new java.awt.Color(51, 255, 51));
        nol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol);
        nol.setBounds(39, 389, 116, 45);

        titik.setBackground(new java.awt.Color(255, 255, 0));
        titik.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        getContentPane().add(titik);
        titik.setBounds(304, 389, 116, 45);

        persen.setBackground(new java.awt.Color(0, 255, 204));
        persen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen);
        persen.setBounds(438, 450, 116, 50);

        akar.setBackground(new java.awt.Color(0, 255, 204));
        akar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        getContentPane().add(akar);
        akar.setBounds(304, 450, 116, 50);

        samadengan.setBackground(new java.awt.Color(0, 255, 204));
        samadengan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(samadengan);
        samadengan.setBounds(39, 450, 250, 50);

        bagi.setBackground(new java.awt.Color(255, 255, 0));
        bagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(438, 389, 116, 45);

        kali.setBackground(new java.awt.Color(255, 255, 0));
        kali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(438, 328, 116, 45);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ATTITUDE IS EVERYTHING");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 530, 280, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Red.svg.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 590, 580);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 40, 470, 50);

        setSize(new java.awt.Dimension(613, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        hasil.getText().length();
        StringBuilder all = new StringBuilder (hasil.getText());
        char end = all.charAt(all.length()-1);
        all.deleteCharAt((all.length()-1));
        hasil.setText(all.toString());
    }//GEN-LAST:event_backspaceActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
        a += "5";
        hasil.setText(a);
    }//GEN-LAST:event_limaActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
        a += ".";
        hasil.setText(a);
    }//GEN-LAST:event_titikActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
        a += "0";
        hasil.setText(a);
    }//GEN-LAST:event_nolActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        a += "1";
        hasil.setText(a);
    }//GEN-LAST:event_satuActionPerformed

    private void duanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duanolActionPerformed
        // TODO add your handling code here:
        a += "00";
        hasil.setText(a);
    }//GEN-LAST:event_duanolActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
        a += "2";
        hasil.setText(a);
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        a += "3";
        hasil.setText(a);
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
        a += "4";
        hasil.setText(a);
    }//GEN-LAST:event_empatActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        a += "6";
        hasil.setText(a);
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
        a += "7";
        hasil.setText(a);
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
        a += "8";
        hasil.setText(a);
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        a += "9";
        hasil.setText(a);
    }//GEN-LAST:event_sembilanActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        hasil.setText("");
        a1=0.0;
        a2=0.0;
        b=0.0;
        a="";
    }//GEN-LAST:event_clearActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        a1=Double.parseDouble(a);
        hasil.setText("+");
        a="";
        pilih=1;
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        a1=Double.parseDouble(a);
        hasil.setText("-");
        a="";
        pilih=2;
    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        a1=Double.parseDouble(a);
        hasil.setText("*");
        a="";
        pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        a1=Double.parseDouble(a);
        hasil.setText("/");
        a="";
        pilih=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            a2 = Double.parseDouble(a);
            b = a1 + a2;
            a = Double.toString(b);
            hasil.setText(a);
            break;
        case 2:
            a2 = Double.parseDouble(a);
            b = a1 - a2;
            a = Double.toString(b);
            hasil.setText(a);
            break;
        case 3:
            a2 = Double.parseDouble(a);
            b = a1 * a2;
            a = Double.toString(b);
            hasil.setText(a);
            break;
        case 4:
            a2 = Double.parseDouble(a);
            b = a1 / a2;
            a = Double.toString(b);
            hasil.setText(a);
            break;
        case 5:
            a2=Double.parseDouble(a);
            b = Math.sqrt(a1);
            a = Double.toString(b);
            hasil.setText(a);
            break;
        case 6:
            b = a1/100;
            a = Double.toString(b);
            hasil.setText(a);
            break;
           
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
        a1=Double.parseDouble(a);
        hasil.setText("√");
        a="";
        pilih=5;
    }//GEN-LAST:event_akarActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        a1=Double.parseDouble(a);
        hasil.setText("%");
        a="";
        pilih=6;
    }//GEN-LAST:event_persenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akar;
    private javax.swing.JButton backspace;
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton duanol;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton exit;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JButton persen;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton titik;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
